Made section for Game Nodes
DanBot-Hosting/DanBotHostingStats pull request #188
Opened 2021-12-16 18:34 UTC by Kyro3400

Before anyone comments yes ik this is stupid but this is something to help keep the nodes list organized since we have a lot of nodes then you can see what nodes are used for what and not get confused

2021-12-16 18:38 UTC, itzJOHv requested changes

2021-12-16 18:38 UTC, itzJOHv commented on bot/discord/serverStatus.js
> +    "Game Server Nodes": [{
make this "Gaming Nodes"

2021-12-16 18:38 UTC, itzJOHv commented on bot/discord/serverUsage.js
> +    "Game Server Nodes": [{
same for this

2021-12-16 18:38 UTC, Kyro3400 commented on bot/discord/serverStatus.js
> +    "Game Server Nodes": [{
Ok

2021-12-16 18:42 UTC, itzJOHv approved these changes
looks good to me now

2022-01-04 21:43 UTC, Jonfirexbox commented
@danielpmc could you merge this?

2022-01-14 22:56 UTC, Kyro3400 commented
Dan could you merge this? I fixed it to be like how the embed is now?

2022-09-20 21:13 UTC, closed without merging