Update api.js
DanBot-Hosting/DanBotHostingStats pull request #205
Opened 2021-12-31 07:57 UTC by WhiteClueGaming

As many people abuse this api by adding users as bot. I have added a check for that and if user is not a bot it will return **404 bot not found**!
Now Dan, you can merge this pr and enable the api for adding bots stats again :)

2021-12-31 08:01 UTC, yuansheng1549 commented
Just use client.users.fetch

2021-12-31 08:02 UTC, WhiteClueGaming commented
Yes I can but there is no client on that router file and because of this api I used. Dans bot will be fine

2021-12-31 08:03 UTC, yuansheng1549 commented
client is defined in global variable

2021-12-31 08:03 UTC, WhiteClueGaming commented
global.client

2021-12-31 14:06 UTC, Darker-Ink commented
This still doesn't fix a ton of problems this has lmao

2021-12-31 14:16 UTC, freddierick commented
Mhm it needs a way for users to variety they own a given bot 

I couldn't figure out a way to do it without the use of a self bot

2021-12-31 14:20 UTC, WhiteClueGaming commented
Theirs some api for that

2021-12-31 14:22 UTC, WhiteClueGaming commented
Ah we can't without making a self bot

2021-12-31 14:38 UTC, freddierick commented
The least invasive approach is telling the user to create a callback URL with a key in it (https://danbot.host/verifyBot/<key>), then using a self bot to call the api discord endpoint that will tell you if it's a valid endpoint or not.
If it's valid that means the user has to own the bot as they set the callback

2021-12-31 14:39 UTC, WhiteClueGaming commented
Ok

2022-02-12 20:23 UTC, itzJOHv requested changes

2022-02-12 20:23 UTC, itzJOHv commented on routes/api.js
> +
```suggestion
    const isBot = await bot.users.fetch(ID).then((u) => u.bot).catch(() => false);
    if (!isBot) return res.status(404).send({error: true, message: "Bot not found"});
```

2022-02-12 20:24 UTC, itzJOHv commented
> The least invasive approach is telling the user to create a callback URL with a key in it ([https://danbot.host/verifyBot/[some](https://danbot.host/verifyBot/%5Bsome) key>), then using a self bot to call the api discord endpoint that will tell you if it's a valid endpoint or not. If it's valid that means the user has to own the bot as they set the callback

update dbh package to send to send owner id from client.application?

2022-09-20 21:13 UTC, closed without merging