If a user doesnt have the donator role when making a donator server, give it to them
DanBot-Hosting/DanBotHostingStats pull request #221
Opened 2022-01-09 09:54 UTC by SirEpiclyAmazing

2022-01-09 21:37 UTC, danielpmc commented
I will leave this until im able to test it. Should be in a few hours

2022-01-09 22:42 UTC, itzJOHv commented
y do u use roles.cache.find() if u can directly do roles.cache.get()

2022-01-12 16:32 UTC, SirEpiclyAmazing commented
> I will leave this until im able to test it. Should be in a few hours

3 days later.....................................................

2022-01-16 14:23 UTC, SirEpiclyAmazing commented
dan wont accept it so closed

2022-01-16 15:13 UTC, itzJOHv commented
why the fuck did u say that this is closed then reopened it

2022-01-17 15:25 UTC, SirEpiclyAmazing commented
cos i can <3

On Sun, 16 Jan 2022 at 15:13, Alex ***@***.***> wrote:

> why the fuck did u say that this is closed then reopened it
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DanBot-Hosting/DanBotHostingStats/pull/221#issuecomment-1013893877>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARVWXXVFNRJUO67UKWN7Q5DUWLODJANCNFSM5LRVHPVQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2022-01-17 15:41 UTC, danielpmc commented
Deleted @SirEpiclyAmazing's reply. Leaked unsub token from replying to email

2022-01-17 15:46 UTC, SirEpiclyAmazing commented
when are u gonna test it

2022-01-17 15:51 UTC, danielpmc commented
Just fixing Node 8 right now, then ill test it after that.

2022-01-17 16:25 UTC, SirEpiclyAmazing commented
pog

On Mon, 17 Jan 2022 at 15:51, danielpmc ***@***.***> wrote:

> Just fixing Node 8 right now, then ill test it after that.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DanBot-Hosting/DanBotHostingStats/pull/221#issuecomment-1014681568>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARVWXXREGNJSYN26TXDGHNDUWQ3HFANCNFSM5LRVHPVQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-01-27 20:16 UTC, DIBSTERYT commented
_10 Days ago..._

2022-01-30 02:01 UTC, danielpmc commented
> Just fixing Node 8 right now, then ill test it after that.

This was checked just after that and there are some issues that will need fixing. Ill submit them here then merge it

2022-01-30 10:39 UTC, Deveroonie commented
what are the issues

2022-02-12 20:09 UTC, itzJOHv requested changes

2022-02-12 20:09 UTC, itzJOHv commented on bot/discord/commands/server/create-donator.js
> +                 if (!message.member.roles.has(allowedRole.id)) {
```suggestion
                 if (!message.member.roles.cache.has(allowedRole.id)) {
```

2022-02-12 20:09 UTC, itzJOHv commented on bot/discord/commands/server/create-donator.js
> +                     let role = message.guild.roles.cache.find(r => r.id === "898041754564046869");
```suggestion
                     const role = message.guild.roles.cache.get("898041754564046869");
```

2022-02-12 20:09 UTC, itzJOHv commented on bot/discord/commands/server/create-donator.js
> +                     message.author.roles.add(role)
```suggestion
                     if (role) message.member.roles.add(role);
```

2022-02-12 20:09 UTC, itzJOHv commented on bot/discord/commands/server/create-donator.js
> +
```suggestion

```

2022-08-03 05:42 UTC, WilliamDavidHarrison commented
Some people don’t donate though, they get given the servers from giveaways, etc.

2022-08-03 09:32 UTC, Sliden101 commented
mfw http://cdn.sliden.tech/MLh99A

2022-08-07 21:16 UTC, Deveroonie commented
I'm not fixing this as I was banned from the DBH Discord.

2022-08-07 21:16 UTC, closed without merging

2022-08-07 22:09 UTC, itzJOHv commented
> I'm not fixing this as I was banned from the DBH Discord.

L

2022-08-08 00:07 UTC, HyptexPvP commented
> I'm not fixing this as I was banned from the DBH Discord.

That's crazy

2022-08-08 10:21 UTC, danielpmc commented
Useless PR. Thread locked