fix server count command (and make it look better)
DanBot-Hosting/DanBotHostingStats pull request #274
Opened 2022-04-17 21:35 UTC by itzJOHv

2022-04-18 00:33 UTC, HyptexPvP approved these changes

2022-04-18 01:29 UTC, Darker-Ink requested changes
debug stuff should be removed. adds useless code for no reason

2022-04-18 06:32 UTC, itzJOHv commented
> debug stuff should be removed. adds useless code for no reason

k

2022-04-19 05:15 UTC, vinc3nz approved these changes

2022-04-27 06:23 UTC, merged