feat: potential fix for premiumfix
DanBot-Hosting/DanBotHostingStats pull request #334
Opened 2023-05-25 23:04 UTC by DEV-DIBSTER

@danielpmc @FC5570 Review.

2023-05-26 22:40 UTC, WilliamDavidHarrison requested changes

2023-05-26 22:40 UTC, WilliamDavidHarrison commented on bot/discord/commands/staff/premiumfix.js
> +        let selectedUser = message.mentions.users.first() || message.guild.members.fetch(args[1]); || message.client.users.cache.get(args[1].match(/[0-9]{18}/).length == 0 ? args[1] : args[1].match(/
> ```js
> args[1].match(/[0-9]{18}/)[0])
> ```

This should be-
```js
args[1].match(/[0-9]{19}/)[0])
```
-to match the new user IDs.

2023-05-27 05:32 UTC, Sliden101 commented
that regex checks for 18 and up if it's 19 old ids won't work

2023-05-27 07:42 UTC, itzJOHv requested changes

2023-05-27 07:42 UTC, itzJOHv commented on bot/discord/commands/staff/premiumfix.js
> +        let selectedUser = message.mentions.users.first() || message.guild.members.fetch(args[1]); || message.client.users.cache.get(args[1].match(/[0-9]{19}/).length == 0 ? args[1] : args[1].match(/
```suggestion
        let selectedUser = message.mentions.users.first() || message.guild.members.fetch(args[1]); || message.client.users.cache.get(args[1].match(/[0-9]{18,19}/).length == 0 ? args[1] : args[1].match(/[0-9]{18,19}/)[0]);
```
:Okay:

2023-05-27 11:32 UTC, WilliamDavidHarrison commented on bot/discord/commands/staff/premiumfix.js
> +        let selectedUser = message.mentions.users.first() || message.guild.members.fetch(args[1]); || message.client.users.cache.get(args[1].match(/[0-9]{19}/).length == 0 ? args[1] : args[1].match(/
Some users have 17 digit IDs

2023-05-27 21:11 UTC, itzJOHv commented on bot/discord/commands/staff/premiumfix.js
> +        let selectedUser = message.mentions.users.first() || message.guild.members.fetch(args[1]); || message.client.users.cache.get(args[1].match(/[0-9]{19}/).length == 0 ? args[1] : args[1].match(/
> Some users have 17 digit IDs

edited thanks

2023-05-31 23:17 UTC, merged