Cleaning out some big files slowly.
DanBot-Hosting/DanBotHostingStats pull request #382
Opened 2023-08-18 02:04 UTC by DEV-DIBSTER

- Trying to make the bot a tiny more readable.

2023-08-18 07:21 UTC, domin-mnd commented
To make it more readable, please remove hardcode in each of the bot file e.g. move Discord IDs to json/js object files.

Also please do not use capital case for variables. This is syntax used for declaring classes and types, variables follow camelCase in most cases. If you're really into changing the case, consider on UPPER_CASE for constant variables.

2023-08-24 00:47 UTC, WilliamDavidHarrison requested changes

2023-08-24 00:47 UTC, WilliamDavidHarrison commented on bot/discord/events/ready.js
> +    //Node Status Channel Embed.
```suggestion
    // Node status embed
```

2023-08-24 00:47 UTC, WilliamDavidHarrison commented on bot/discord/events/ready.js
> +    //Something to do with invites.
```suggestion
    // Fetch and store guild invites
```

2023-08-24 00:47 UTC, WilliamDavidHarrison commented on bot/discord/events/ready.js
>      //Check make sure create account channels are closed after a hour
```suggestion
    // Close create account channels after a hour
```

2023-08-24 00:47 UTC, WilliamDavidHarrison commented on bot/discord/events/message.js
> +    // After command remove all clone traces
```suggestion
    // Remove all clone traces after running command
```

2023-08-24 00:47 UTC, WilliamDavidHarrison commented on bot/discord/events/message.js
> +            // Double check the user is allowed to use this command.
```suggestion
            // Double check the user is allowed to use this command
```

2023-08-24 00:47 UTC, WilliamDavidHarrison commented on bot/discord/events/message.js
> +    if (message.author.bot) return; // To stop bots from creating accounts, tickets and more.
```suggestion
    if (message.author.bot) return; // Stop bots from running commands
```

2023-08-24 00:47 UTC, WilliamDavidHarrison commented on bot/discord/events/message.js
> +    if (message.channel.type === "dm") return; // Stops commands working in dms
```suggestion
    if (message.channel.type === "dm") return; // Stop commands in DMs
```

2023-08-24 00:47 UTC, WilliamDavidHarrison commented on bot/discord/events/message.js
> +        // Checks if the member is one of the members allowed. If it is, allows the member to send messages on behalf of the bot.
```suggestion
        // Allow users to send messages on behalf of the bot if they are allowed
```

2023-08-24 00:47 UTC, WilliamDavidHarrison commented on bot/discord/events/message.js
> +    // Auto reactions on suggestions channels
```suggestion
    // Suggestions channels reactions
```

2023-08-24 00:47 UTC, WilliamDavidHarrison commented on bot/discord/events/message.js
> +    // Checks the amount of member pinged in a message.
```suggestion
    // Ban members which ping 20+ users
```

2023-08-24 00:48 UTC, WilliamDavidHarrison approved these changes

2023-08-24 20:03 UTC, merged