feat: Account deletion command.
DanBot-Hosting/DanBotHostingStats pull request #454
Opened 2024-09-07 21:22 UTC by DEV-DIBSTER

- Allows a user to delete their panel account.
- Deletes their userData.
- Deletes their userPrem.

2024-09-08 00:52 UTC, wdhdev commented
Why delete premium servers?

2024-09-08 00:57 UTC, DEV-DIBSTER commented
> Why delete premium servers?

If users at DBH only had a panel account and no other data, we can confirm that a single command ran by them would be sufficient enough for account deletion.

2024-09-08 02:46 UTC, wdhdev commented
What if they do have premium servers? Why would we delete them?

2024-09-08 03:44 UTC, DEV-DIBSTER commented
> What if they do have premium servers? Why would we delete them?

It deletes their account, so storing premium servers doesn't make sense in my mind.

2024-09-08 03:57 UTC, wdhdev commented
They paid for them though. What if they want them in future?

2024-09-08 03:58 UTC, Microwave-6443 commented
> They paid for them though. What if they want them in future?

Why would you want to delete your account if you intend to use the service in the future? Especially if you've spent money on it, in this case, for premium servers.

2024-09-08 20:42 UTC, xrap1dx commented
> Why would you want to delete your account if you intend to use the service in the future? Especially if you've spent money on it, in this case, for premium servers.

But if you ever came back to DBH then you want your premium servers? 

I feel like you should be able to use a command then it emails the panel
Account and you click confirm and within 30 days the Data gets deleted & Maybe a “Account Disable” feature?

2024-09-08 20:59 UTC, Microwave-6443 commented
> > Why would you want to delete your account if you intend to use the service in the future? Especially if you've spent money on it, in this case, for premium servers.
> 
> But if you ever came back to DBH then you want your premium servers?
> 
> I feel like you should be able to use a command then it emails the panel Account and you click confirm and within 30 days the Data gets deleted & Maybe a “Account Disable” feature?

I don't think you really succeeded in countering my point here, because again, they're likely not thinking of coming back, and that wouldn't be the host's fault. Account deletion requests are intended to delete **ALL** data related to the account, not just select pieces.

As for a 30-day confirmation period, I think that would help cement the user's decision to delete their data and it would give them plenty of time to go back if they decide that they don't actually want to delete their data.

2024-09-09 01:50 UTC, wdhdev requested changes

2024-09-09 01:50 UTC, wdhdev commented on src/commands/user/delete.js
> +
```suggestion
```

2024-09-09 02:04 UTC, Microwave-6443 commented on src/commands/user/delete.js
> +
I guess he disagreed with us. 🤣

2024-09-09 02:10 UTC, DEV-DIBSTER commented on src/commands/user/delete.js
> +
😂 Real.

2024-09-09 02:11 UTC, merged